#!/bin/bash

# Usage message
usage="usage: $0 encryptionport"

# Use the standard version of echo
echo=/bin/echo

# Make sure we have the right number of arguments
if test $# -ne 1
then
	${echo} $usage 1>&2
	exit 1
fi

# Clean up any previous runs
${echo} '#Initializing - Cleaning up - ignore Operation Not Permitted errors'
killall -q -u $USER enc_client
killall -q -u $USER enc_server
rm -f ciphertext*
rm -f key*

# Record the port passed in
encport=$1

# Run the encryption server daemon
./enc_server $encport &

sleep 5

${echo}
${echo} '#-----------------------------------------'
${echo} '#START OF TESTING SCRIPT'
${echo} '#keygen 70000 > key70000'
./keygen 70000 > key70000
${echo} "#5 POINTS: Number of characters in key70000, should be 70001:"
[ -s key70000 ] || rm -f key70000 
wc -m key70000
${echo}
${echo} "#-----------------------------------------"
${echo} '#enc_client plaintext1 key70000 $encport > ciphertext1'
./enc_client plaintext1 key70000 $encport > ciphertext1
${echo} "#10 POINTS: ciphertext1 must exist"
[ -s ciphertext1 ] || rm -f ciphertext1 
if [ -f ciphertext1 ]; then ${echo} 'ciphertext1 exists!'; else ${echo} 'ciphertext1 DOES NOT EXIST'; fi 
${echo}
${echo} '#-----------------------------------------'
${echo} '#10 POINTS: ciphertext1 must be same number of chars as source'
${echo} '#wc -m plaintext1'
wc -m plaintext1
${echo} '#Should be same: wc -m ciphertext1'
wc -m ciphertext1
${echo}
${echo} '#-----------------------------------------'
${echo} '#5 POINTS: ciphertext1 should look encrypted'
cat ciphertext1
${echo}
${echo} '#-----------------------------------------'
${echo} '#20 POINTS: concurrent test of encryption - look for properly-sized ciphertext# files'
rm -f ciphertext*
./enc_client plaintext1 key70000 $encport > ciphertext1 &
./enc_client plaintext2 key70000 $encport > ciphertext2 &
./enc_client plaintext3 key70000 $encport > ciphertext3 &
./enc_client plaintext4 key70000 $encport > ciphertext4 &
${echo} 'Ten second sleep, your program must complete in this time'
sleep 10
ls -la
${echo}
${echo} '#-----------------------------------------'
${echo} '#Cleaning up - ignore Operation Not Permitted errors'
killall -q -u $USER enc_client
killall -q -u $USER enc_server
rm -f ciphertext*
rm -f key*
${echo}
${echo} '#SCRIPT COMPLETE'
